#!/usr/bin/env python

obj = bld(
	features = 'cc cprogram',
	packages = 'gtk+-2.0 gtksourceview-2.0 gio-2.0 gee-1.0',
	target   = 'vaedit',
	uselib   = 'GTK GLIB GTKSOURCEVIEW GIO GEE',
	)

obj.find_sources_in_dirs('.')
